# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 22:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=255)),
                ('starting_year', models.CharField(max_length=10)),
                ('anticipated_graduation_year', models.CharField(max_length=10)),
                ('graduation_year', models.CharField(max_length=10)),
                ('gpa', models.FloatField(default=0.0)),
                ('general_elective_preference', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), size=None)),
                ('major_elective_preference', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), size=None)),
                ('good_standing', models.BooleanField(default=False)),
            ],
        ),
    ]
