# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csun_calendar', '0002_auto_20180420_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gpa',
            new_name='cumulative_gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='good_standing',
        ),
        migrations.AddField(
            model_name='user',
            name='year_four_semester_one_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_four_semester_two_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_four_summer_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_one_semester_one_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_one_semester_two_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_one_summer_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_three_semester_one_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_three_semester_two_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_three_summer_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_two_semester_one_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_two_semester_two_gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='year_two_summer_gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
