# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csun_calendar', '0003_auto_20180423_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anticipated_graduation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='cumulative_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_four_semester_one_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_four_semester_two_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_four_summer_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_one_semester_one_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_one_semester_two_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_one_summer_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_three_semester_one_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_three_semester_two_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_three_summer_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_two_semester_one_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_two_semester_two_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_two_summer_gpa',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
