# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 22:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csun_calendar', '0004_auto_20180423_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='general_elective_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_elective_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None), size=None),
        ),
    ]
