# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 23:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csun_calendar', '0006_auto_20180423_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='major_elective_preference',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_four_semester_one',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_four_semester_two',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_four_summer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=None, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_one_semester_one',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_one_semester_two',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_one_summer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=None, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_three_semester_one',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_three_semester_two',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_three_summer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=None, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_two_semester_one',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_two_semester_two',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_two_summer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=None, size=None), null=True, size=None),
        ),
    ]
