# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 03:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csun_calendar', '0011_auto_20180504_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='general_electives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], null=True, size=None),
        ),
    ]
